title: mulpre13 dev blog
email: mulpre13@gmail.com
baseurl: ""
url: "https://mulpre13.github.io"

theme: jekyll-theme-simplex
plugins:
 - jekyll-feed

logo_img: /assets/img/icons/golasblog_logo.svg #Absolute path to the logo. If not specified, the title will be displayed instead.
copyright: © woosung 2021  #Your copyright.

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
